### ISSUE TITLE
Running non-interactively

### ISSUE THREAD

**Issue by cburza** [haunt98/changeloguru#33]
I am not able to run the command in a non interactive way.

```
generate --version v2.0.0 --to v1.0.1 --scope acm --interactive false
Input version (`VERSION` to generate, follow Semantic Versioning):
```

It always asks for input.

**Comment by haunt98** [comment]
Maybe there is a bug. Let me try to re create

**Comment by haunt98** [comment]
Hy @cburza, I have fixed the issue. Could you try again, but without `--interactive`.
After some time playing with urfave/cli, I think that even `--interactive false` trigger that.

You should use like this:

```sh
generate --version v2.0.0 --to v1.0.1 --scope acm
```
