### ISSUE TITLE
add clean work dir option

### ISSUE THREAD

**Issue by fnoopv** [haunt98/changeloguru#69]
Sometimes we want the work area to be clean when executing changeloguru to avoid some errors. Can we add a flag to control these?

**Comment by haunt98** [comment]
Hi @fnoopv, I don't understand which "work area" you want to clean. Is this some files or directories...?

**Comment by fnoopv** [comment]
like release-it config option `requireCleanWorkingDir` : 
https://github.com/release-it/release-it/blob/56787b5147919a328c4878a85847cbd2fa88d6f8/config/release-it.json#L5
